### ISSUE TITLE
Turn on the artifacts output layout

### ISSUE THREAD

**Issue by premun** [eduherminio/AdventOfCode.MultiYearTemplate#3]
I'd suggest turning on the [artifacts output layout](https://learn.microsoft.com/en-us/dotnet/core/sdk/artifacts-output) for the repo.

It just means adding this to `Directory.Build.props`:
```xml
  <UseArtifactsOutput>true</UseArtifactsOutput>
```

It's just much better experience once you start using it.

**Comment by eduherminio** [comment]
Thanks for the suggestion Přemek!
